apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: abzaek/notification:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notification-config
            - secretRef:
                name: notification-secret
          